service: spec_driven_app

image: ghcr.io/apperph/github-actions-test

servers:
  web:
    - rails-test-lightsail

proxy:
  ssl: false
  host: 52.77.159.239

registry:
  server: ghcr.io
  username: apperph
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: ubuntu
