service: spec_driven_app

image: ghcr.io/apperph/github-actions-test

servers:
  web:
    - 13.213.250.166

proxy:
  ssl: false
  host: 13.213.250.166

registry:
  server: ghcr.io
  username: apperph
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PORT: 80
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: ubuntu
  keys_only: true
  config: false
